import React, {useState} from "react";
import { useNavigate } from "react-router-dom";

/**
 * CreateNote component allows users to create a new note with a title and details.
 * It generates a unique ID for each note, captures the creation date, and adds the note
 * to the notes collection. Users can navigate back or save the note which redirects to home.
 */

// Prompt: #sym:app.post('/notes') callback I want to utilise this method to add notes in this page
// Some code is also provided by the suggestions in copilot

const CreateNote = () => {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [error, setError] = useState("");
  const navigate = useNavigate(); // For navigation after saving or deleting

  // Generated by copilot using the prompt used above
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    if (!title || !content) {
      setError("Title and content are required.");
      return;
    }

    try {
      const response = await fetch("http://localhost:5042/notes", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ title, content }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        setError(errorData.error || "Failed to create note.");
        return;
      }

      const newNote = await response.json();
      console.log("Note created:", newNote);
      navigate("/");
    } catch (err) {
      setError("An error occurred while creating the note.");
    }
  };

return (
    <section>
      <h1>Create Note</h1>
      {error && <p style={{ color: "red" }}>{error}</p>}
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="title">Title:</label>
          <input
            type="text"
            id="title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="content">Content:</label>
          <textarea
            id="content"
            value={content}
            onChange={(e) => setContent(e.target.value)}
          ></textarea>
        </div>
        <button type="submit">Save Note</button>
      </form>
    </section>
  );
};

export default CreateNote;
